# Generated by Django 3.0.14 on 2022-02-17 11:28

import ProcessAdminRestApi.models.fields.XLSX_field
import ProcessAdminRestApi.models.upload_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('is_calculated', ProcessAdminRestApi.models.upload_model.IsCalculatedField(default=False)),
                ('calculate', ProcessAdminRestApi.models.upload_model.CalculateField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('zip_file', models.FileField(blank=True, max_length=300, null=True, upload_to='upload_files/zip_file')),
                ('renaming_table', models.FileField(blank=True, max_length=300, null=True, upload_to='upload_files/renaming_table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_file', ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(upload_to='download/zip_file')),
                ('xlsx_report', ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(upload_to='download/xlsx_report')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.UploadFile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='downloadfile',
            constraint=models.UniqueConstraint(fields=('upload',), name='defining_fields_DownloadFile'),
        ),
    ]
