# Generated by Django 4.0.5 on 2022-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationlog',
            name='frontendId',
            field=models.TextField(default='-1'),
        ),
        migrations.AddField(
            model_name='userchangelog',
            name='frontendId',
            field=models.TextField(default='-1'),
        ),
    ]
