# Generated by Django 4.0.10 on 2023-04-30 12:33

import ProcessAdminRestApi.models.fields.XLSX_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0002_calculationlog_frontendid_userchangelog_frontendid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filter', models.TextField(null=True)),
                ('logfile', ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(default='', upload_to='')),
                ('logfile_timesheet', ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(default='', upload_to='')),
                ('logfile_events', ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(default='', upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='userchangelog',
            old_name='frontendId',
            new_name='calculationId',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='frontendId',
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='calculationId',
            field=models.TextField(default='test_id'),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='message_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='trigger_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rename_based_on_file_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rename_based_on_file_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchangelog',
            name='traceback',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('filter',), name='defining_fields_Log'),
        ),
    ]
